### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by wxce** [HexCodeFFF/melutils#1]
tables and columns needed to run nitroroles.py?

**Comment by wxce** [comment]
i just noticed main.py and makedatabase.sql please do not mind me

**Comment by machineonamission** [comment]
nitroroles uses `server_config` and `booster_roles`, as documented in [makedatabase.sql](https://github.com/HexCodeFFF/melutils/blob/master/makedatabase.sql), though i reccomend setting up the entire DB with the script

**Comment by machineonamission** [comment]
oh
lol
